//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Development/Projects/playground/antlr_sample/src\Csv.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace Grammar {
using System;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class CsvLexer : Lexer {
	public const int
		T__0=1, T__1=2, COMMA=3, TEXT=4, STRING=5;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "COMMA", "TEXT", "STRING"
	};


	public CsvLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'\r'", "'\n'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "COMMA", "TEXT", "STRING"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Csv.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\a#\b\x1\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x3\x2\x3\x2\x3\x3\x3\x3"+
		"\x3\x4\x3\x4\x3\x5\x6\x5\x15\n\x5\r\x5\xE\x5\x16\x3\x6\x3\x6\x3\x6\x3"+
		"\x6\a\x6\x1D\n\x6\f\x6\xE\x6 \v\x6\x3\x6\x3\x6\x2\x2\a\x3\x3\x5\x4\a\x5"+
		"\t\x6\v\a\x3\x2\x4\x6\x2\f\f\xF\xF$$..\x3\x2$$%\x2\x3\x3\x2\x2\x2\x2\x5"+
		"\x3\x2\x2\x2\x2\a\x3\x2\x2\x2\x2\t\x3\x2\x2\x2\x2\v\x3\x2\x2\x2\x3\r\x3"+
		"\x2\x2\x2\x5\xF\x3\x2\x2\x2\a\x11\x3\x2\x2\x2\t\x14\x3\x2\x2\x2\v\x18"+
		"\x3\x2\x2\x2\r\xE\a\xF\x2\x2\xE\x4\x3\x2\x2\x2\xF\x10\a\f\x2\x2\x10\x6"+
		"\x3\x2\x2\x2\x11\x12\a.\x2\x2\x12\b\x3\x2\x2\x2\x13\x15\n\x2\x2\x2\x14"+
		"\x13\x3\x2\x2\x2\x15\x16\x3\x2\x2\x2\x16\x14\x3\x2\x2\x2\x16\x17\x3\x2"+
		"\x2\x2\x17\n\x3\x2\x2\x2\x18\x1E\a$\x2\x2\x19\x1A\a$\x2\x2\x1A\x1D\a$"+
		"\x2\x2\x1B\x1D\n\x3\x2\x2\x1C\x19\x3\x2\x2\x2\x1C\x1B\x3\x2\x2\x2\x1D"+
		" \x3\x2\x2\x2\x1E\x1C\x3\x2\x2\x2\x1E\x1F\x3\x2\x2\x2\x1F!\x3\x2\x2\x2"+
		" \x1E\x3\x2\x2\x2!\"\a$\x2\x2\"\f\x3\x2\x2\x2\x6\x2\x16\x1C\x1E\x2";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace Grammar
