//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Development/Projects/antlr/CodeSharper-grammars/src/CodeQuery/v1_1\CodeQuery.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CodeQuery"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface ICodeQueryVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeQuery.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] CodeQuery.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionMethodCall</c>
	/// labeled alternative in <see cref="CodeQuery.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionMethodCall([NotNull] CodeQuery.ExpressionMethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionSelector</c>
	/// labeled alternative in <see cref="CodeQuery.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionSelector([NotNull] CodeQuery.ExpressionSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionInBrackets</c>
	/// labeled alternative in <see cref="CodeQuery.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionInBrackets([NotNull] CodeQuery.ExpressionInBracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeQuery.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] CodeQuery.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCallParameterValueWithExpression</c>
	/// labeled alternative in <see cref="CodeQuery.methodCallParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallParameterValueWithExpression([NotNull] CodeQuery.MethodCallParameterValueWithExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCallParameterValueWithConstant</c>
	/// labeled alternative in <see cref="CodeQuery.methodCallParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallParameterValueWithConstant([NotNull] CodeQuery.MethodCallParameterValueWithConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCallParameterValueWithIdentifier</c>
	/// labeled alternative in <see cref="CodeQuery.methodCallParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallParameterValueWithIdentifier([NotNull] CodeQuery.MethodCallParameterValueWithIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeQuery.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] CodeQuery.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeQuery.selectableElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectableElement([NotNull] CodeQuery.SelectableElementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PseudoSelectorWithConstant</c>
	/// labeled alternative in <see cref="CodeQuery.pseudoSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudoSelectorWithConstant([NotNull] CodeQuery.PseudoSelectorWithConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PseudoSelectorWithIdentifier</c>
	/// labeled alternative in <see cref="CodeQuery.pseudoSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudoSelectorWithIdentifier([NotNull] CodeQuery.PseudoSelectorWithIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeQuery.selectorAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectorAttribute([NotNull] CodeQuery.SelectorAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeQuery.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] CodeQuery.ConstantContext context);
}
